name: publish

on:
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME}}
  ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD}}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGN_SECRET_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGN_SECRET_PWD }}

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  # Don't cancel midway through publishing if another workflow is triggered, it might cause partial publications
  cancel-in-progress: false

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Cache Kotlin Konan
        uses: actions/cache@v4
        with:
          path: ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish
        run: ./gradlew publish --no-parallel --stacktrace
