name: publish

on:
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME}}
  ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD}}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGN_SECRET_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGN_SECRET_PWD }}

jobs:
  publish:
    runs-on: macos-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "zulu"
          cache: "gradle"

      - name: Cache Kotlin Konan
        id: cache-kotlin-konan
        uses: actions/cache@v3
        with:
          path: ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}

      - name: Build
        uses: gradle/gradle-build-action@v2

      - name: Publish
        run: ./gradlew publish --no-parallel --stacktrace
